# Generated by Django 3.1.3 on 2021-03-19 22:26

import colors_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('red', models.IntegerField(validators=[colors_app.validators.color_channel_validator])),
                ('green', models.IntegerField(validators=[colors_app.validators.color_channel_validator])),
                ('blue', models.IntegerField(validators=[colors_app.validators.color_channel_validator])),
            ],
        ),
    ]
